FROM php:7.1.11-apache
RUN pecl install xdebug-2.5.0
RUN { \
		echo 'log_errors = On';\
		echo 'display_errors = Off';\
		echo 'error_log = /var/log/apache2/error.log'; \
		echo 'zend_extension=xdebug.so';\
        echo 'xdebug.default_enable = 1';\
        echo 'xdebug.remote_autostart = 1';\
        echo 'xdebug.remote_enable = 1';\
        echo 'xdebug.remote_port = 9000';\
        echo 'xdebug.remote_host = docker.for.mac.localhost';\
        echo 'session.save_path = /tmp';\
} | tee "/usr/local/etc/php/php.ini"
RUN a2enmod headers; \
a2enmod rewrite; \
service apache2 restart
